export { default as ArticlesPage } from "./ArticlesPage/ArticlesPage"
export { default as AboutPage } from "./AboutPage/AboutPage"
export { default as NotFound } from "./NotFound/NotFound"
export { default as Dashboard } from "./Dashboard/Dashboard"
export { default as CreateArticle } from "./CreateArticle/CreateArticle"
export { default as ArticlePage } from "./ArticlePage/ArticlePage"
export { default as RegisterPage } from "./RegisterPage/RegisterPage"
export { default as LoginPage } from "./LoginPage/LoginPage"
export {default as MyArticlesPage} from "./MyArticlesPage/MyArticlesPage"
